name: Platform Tests & Build
on: [push]

jobs:
  platform_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.19]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Set Version
      run: make set-version
      
    - uses: WillAbides/setup-go-faster@v1.7.0
      with:
        go-version: ${{ matrix.go-version }}

    - name: Get dependencies
      run: sudo apt-get update && sudo apt-get install bc make
      if: ${{ runner.os == 'Linux' }}

    - name: Tests
      run: go test -tags ci ./...

    - name: Wayland Tests
      run: go test -tags ci,wayland ./...
      if: ${{ runner.os == 'Linux' }}

    - name: Update coverage
      run: |
        GO111MODULE=off go get github.com/mattn/goveralls
        set -e
        go test -tags ci -covermode=atomic -coverprofile=coverage.out ./...
        coverage=`go tool cover -func coverage.out | grep total | tr -s '\t' | cut -f 3 | grep -o '[^%]*'`
        if (( $(echo "$coverage < 1" | bc) )); then echo "Test coverage lowered"; echo "exit 1"; fi
      if: ${{ runner.os == 'Linux' }}

    - name: Update PR Coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.out
      if: ${{ runner.os == 'Linux' && matrix.go-version == '1.19' }}

    - name: Build binaries
      env:
        GOOS: linux
        GOARCH: amd64
      working-directory: .
      run: |
        make build-linux
        make build-windows
        make build-darwin
      if: ${{runner.os == 'Linux'}}

    - uses: "marvinpinto/action-automatic-releases@latest"
      if: github.ref == 'refs/heads/master'
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.VERSION }}.${{ github.run_number }}"
        prerelease: true
        title: "${{ env.VERSION }}.${{ github.run_number }}"
        files: |
          bin/talkeq-${{ env.VERSION }}-linux-x64
          bin/talkeq-${{ env.VERSION }}-win-x64.exe
          bin/talkeq-${{ env.VERSION }}-win-x86.exe
          bin/talkeq-${{ env.VERSION}}-darwin-x64
